In [26]:
import numpy as np
import pandas as pd

In [27]:
skin_acne = pd.read_csv("/Users/krishprakash/Desktop/ML/archive/train/_annotations.csv")
skin_acne.head(10)

filename  width  height class  \
0  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
1  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
2  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
3  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
4  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
5  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
6  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
7  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...    512     512  spot   
8  26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2d...    512     512  acne   
9  26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2d...    512     512  acne   

   xmin  ymin  xmax  ymax  
0   331   280   346   290  
1   343   302   359   315  
2   355   331   373   343  
3    98   201   124   216  
4   258   119   282   138  
5   328   321   349   336  
6   112   371   132   391  
7   360   292   378   309  
8   158   317   176   333  
9   322   400   339   411

In [28]:
skin_acne = skin_acne.drop(columns = ["width", "height", "xmin", "ymin", "ymax", "xmax"])
skin_acne.head(10)

filename class
0  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
1  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
2  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
3  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
4  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
5  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
6  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
7  16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
8  26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2d...  acne
9  26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2d...  acne

In [29]:
skin_acne["class"]

0       spot
1       spot
2       spot
3       spot
4       spot
        ... 
7839    acne
7840    acne
7841    acne
7842    acne
7843    acne
Name: class, Length: 7844, dtype: object

In [30]:
skin_acne

filename class
0     16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
1     16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
2     16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
3     16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
4     16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a0...  spot
...                                                 ...   ...
7839  17331_png_jpg.rf.500920756b615b1c71b541fe96e9c...  acne
7840  17331_png_jpg.rf.500920756b615b1c71b541fe96e9c...  acne
7841  17331_png_jpg.rf.500920756b615b1c71b541fe96e9c...  acne
7842  49178_png_jpg.rf.4ec1f28fdc9061a68f00beccc1d36...  acne
7843  49178_png_jpg.rf.4ec1f28fdc9061a68f00beccc1d36...  acne

[7844 rows x 2 columns]

In [31]:
filenames = [fname for fname in skin_acne["filename"]]
copy_filenames = filenames

In [32]:
import os

In [33]:
len(filenames)

7844

In [34]:
len(os.listdir("/Users/krishprakash/Desktop/ML/archive/valid"))

405

In [58]:
i = 0
new_filenames = []
for fname in os.listdir("/Users/krishprakash/Desktop/ML/archive/train"):
    if fname in filenames:
        new_filenames.append(fname)
        i= i+1
    
        
        
print(i)
        
        

1574


In [59]:
len(new_filenames)

1574

In [47]:
filenames[:10]

['16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '16262_png_jpg.rf.c6cb30e0b2ede8bcff6438cebd1a02f3.jpg',
 '26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2de91.jpg',
 '26817_png_jpg.rf.c6202600e22acb9b85ce311cf0a2de91.jpg']

In [49]:
if "11298_png_jpg.rf.7b5f59cb61bc7705b8fd32b2aa88e87a.jpg" in filenames:
    print("TRUE")

TRUE


In [60]:
new_filenames[:30]

['11298_png_jpg.rf.7b5f59cb61bc7705b8fd32b2aa88e87a.jpg',
 'OgwQpnTdFOU_jpg.rf.ac3f2a68cf21e17eefa543f87049536e.jpg',
 '25474_png_jpg.rf.5f8ddfcdd6157c76b39d10a3caee2e3e.jpg',
 '47305_png_jpg.rf.93b496fbf928341f3551623ad73cbcd2.jpg',
 '41709_png_jpg.rf.8cc1bdddb65dbd8f8fea0ccae99cd840.jpg',
 '68956_png_jpg.rf.f93af9b6d6491bc83c7621a75303c336.jpg',
 '08083_png_jpg.rf.671163d845d96fe980b6f900b4d3fbfe.jpg',
 '21837_png_jpg.rf.81b6c9445cc0081d30c35c5f1b50facf.jpg',
 '21839_png_jpg.rf.404170fa907d30f4d95dd5d09ae976f7.jpg',
 '24761_png_jpg.rf.5862aa9da9c27d1ab84b605732bf127c.jpg',
 '41083_png_jpg.rf.dd5feeb916add7abceb6285dad4780f5.jpg',
 '17168_png_jpg.rf.66cb84c401d5e58d4f64cc9e682c6f5a.jpg',
 '23435_png_jpg.rf.96c1f72d0f6577ca7ed6dad530aa9c1e.jpg',
 '33880_png_jpg.rf.4f528319c3a8d90ebdd188bd262c492e.jpg',
 '44253_png_jpg.rf.8ae8411f7547e64ce08a5372d6387865.jpg',
 '00025_png_jpg.rf.d349f9f6f885ebf1cc6310f9f2327a06.jpg',
 '02553_png_jpg.rf.daa32d046603cf126f1073f9af7c492c.jpg',
 '24633_png_

In [61]:
filenames = new_filenames

In [62]:
len(filenames)

1574

In [66]:
dd = {"Name" : ["Anil", "Bhawna", "John", "Perlyn", "Dani"], "Sex": ["Male", "Female", "Male", "Female", "Female"]}
df = pd.DataFrame(dd)
df

Name     Sex
0    Anil    Male
1  Bhawna  Female
2    John    Male
3  Perlyn  Female
4    Dani  Female

In [70]:
sex = np.array(df["Sex"])
sex


array(['Male', 'Female', 'Male', 'Female', 'Female'], dtype=object)

In [71]:
sex_type = np.unique(sex)

In [73]:
sex_type

array(['Female', 'Male'], dtype=object)

In [74]:
sex[0] == sex_type

array([False,  True])

In [75]:
boolean_label = []
for t in sex:
    boolean_label.append(t == sex_type)

boolean_label

[array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array([ True, False])]

In [80]:
x = np.array(boolean_label).astype(int)
x

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0]])