In [2]:
# Introduction to Scikit Learn

In [3]:
#An end ot rnf scikit-learn workflow

In [8]:
# 1. get the data ready 
import pandas as pd
import numpy as np

heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [9]:
# create X (features matrix)
x = heart_disease.drop("target", axis = 1)

# creste y (labels)
y = heart_disease["target"]

In [10]:
# 2. choose the right model and hyperparameter 
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [11]:
# 3. fit the model to the training data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2) 

In [14]:
# x_test[:2]

In [7]:
clf.fit(x_train, y_train);

In [8]:
# make a prediction 

# y_label = clf.predict(np.array([0,2,3,4]))

y_preds = clf.predict(x_test)
y_preds

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1])

In [9]:
y_test

14     1
249    0
30     1
168    0
231    0
      ..
270    0
151    1
272    0
68     1
115    1
Name: target, Length: 61, dtype: int64

In [10]:
# 4. evaluate the model on training data and test data

clf.score(x_train, y_train)


1.0

In [11]:
clf.score(x_test, y_test)

0.8032786885245902

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.84      0.79      0.82        34
           1       0.76      0.81      0.79        27

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



In [13]:
confusion_matrix(y_test, y_preds)

array([[27,  7],
       [ 5, 22]])

In [14]:
accuracy_score(y_test, y_preds)

0.8032786885245902

In [15]:
# 5. improve the model
# try different amopunt of n_estimators

np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators....")
    clf = RandomForestClassifier(n_estimators = i).fit(x_train, y_train)
    print(f"Model accuracy on test set : {clf.score(x_test, y_test)*100}")

# clf = RandomForestClassifier().fit(x_train, y_train)

Trying model with 10 estimators....
Model accuracy on test set : 83.60655737704919
Trying model with 20 estimators....
Model accuracy on test set : 83.60655737704919
Trying model with 30 estimators....
Model accuracy on test set : 77.04918032786885
Trying model with 40 estimators....
Model accuracy on test set : 83.60655737704919
Trying model with 50 estimators....
Model accuracy on test set : 83.60655737704919
Trying model with 60 estimators....
Model accuracy on test set : 80.32786885245902
Trying model with 70 estimators....
Model accuracy on test set : 77.04918032786885
Trying model with 80 estimators....
Model accuracy on test set : 81.9672131147541
Trying model with 90 estimators....
Model accuracy on test set : 80.32786885245902


In [16]:
# 6. save the model and load it(pickling)

import pickle

pickle.dump(clf, open("random_forest_heart_disease_mk1.pkl", "wb"))

In [17]:
loaded_model = pickle.load(open("random_forest_heart_disease_mk1.pkl", "rb"))
loaded_model.score(x_test, y_test)

0.8032786885245902

In [18]:
###################

In [19]:
# Make predictions using a machine learning model
# 2 ways to make predictions - 
# 1. predict()
# 2. predict_proba()

In [20]:
clf.predict(x_test)


array([1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1])

In [21]:
y_test

14     1
249    0
30     1
168    0
231    0
      ..
270    0
151    1
272    0
68     1
115    1
Name: target, Length: 61, dtype: int64

In [22]:
# compare predictions to truth tables to evaluate the model / finding the accuracy 

y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

0.8032786885245902

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8032786885245902

In [24]:
# make preictions with predict_proba()
# predict_proba() returns probabilities of a classification label
#  use predict_proba() when more confident model is required; example - when you need answers or samples with more than 85% accuracy only
clf.predict_proba(x_test[:5])

array([[0.13333333, 0.86666667],
       [0.55555556, 0.44444444],
       [0.14444444, 0.85555556],
       [0.87777778, 0.12222222],
       [0.93333333, 0.06666667]])

In [25]:
clf.predict(x_test[:5])

array([1, 0, 1, 0, 0])