In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [5]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [15]:
df = sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(['No', 'Yes'])

array([0, 1])

In [25]:
df['smoker'].replace({'Yes': 1, 'No':0}, inplace=True)

/var/folders/lr/vhwgcn3d1td6h5t5_lrvq28c0000gn/T/ipykernel_2770/3975350350.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['smoker'].replace({'Yes': 1, 'No':0}, inplace=True)
/var/folders/lr/vhwgcn3d1td6h5t5_lrvq28c0000gn/T/ipykernel_2770/3975350350.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', 

In [27]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female      0   Sun  Dinner     2
1         10.34  1.66    Male      0   Sun  Dinner     3
2         21.01  3.50    Male      0   Sun  Dinner     3
3         23.68  3.31    Male      0   Sun  Dinner     2
4         24.59  3.61  Female      0   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male      0   Sat  Dinner     3
240       27.18  2.00  Female      1   Sat  Dinner     2
241       22.67  2.00    Male      1   Sat  Dinner     2
242       17.82  1.75    Male      0   Sat  Dinner     2
243       18.78  3.00  Female      0  Thur  Dinner     2

[244 rows x 7 columns]

In [74]:
df_encode = pd.get_dummies(df, drop_first=True)
df_encode

total_bill   tip  size  sex_Female  smoker_0  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01     2        True      True    False    False     True   
1         10.34  1.66     3       False      True    False    False     True   
2         21.01  3.50     3       False      True    False    False     True   
3         23.68  3.31     2       False      True    False    False     True   
4         24.59  3.61     4        True      True    False    False     True   
..          ...   ...   ...         ...       ...      ...      ...      ...   
239       29.03  5.92     3       False      True    False     True    False   
240       27.18  2.00     2        True     False    False     True    False   
241       22.67  2.00     2       False     False    False     True    False   
242       17.82  1.75     2       False      True    False     True    False   
243       18.78  3.00     2        True      True    False    False    False   

     time_Dinner  
0           True  
1           True  
2           True  
3           True  
4           True  
..           ...  
239         True  
240         True  
241         True  
242         True  
243         True  

[244 rows x 9 columns]

In [77]:
df_encode[['sex_Female', 'smoker_0', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Dinner']] = df_encode[['sex_Female', 'smoker_0', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Dinner']].astype(int)
df_encode

total_bill   tip  size  sex_Female  smoker_0  day_Fri  day_Sat  day_Sun  \
0         16.99  1.01     2           1         1        0        0        1   
1         10.34  1.66     3           0         1        0        0        1   
2         21.01  3.50     3           0         1        0        0        1   
3         23.68  3.31     2           0         1        0        0        1   
4         24.59  3.61     4           1         1        0        0        1   
..          ...   ...   ...         ...       ...      ...      ...      ...   
239       29.03  5.92     3           0         1        0        1        0   
240       27.18  2.00     2           1         0        0        1        0   
241       22.67  2.00     2           0         0        0        1        0   
242       17.82  1.75     2           0         1        0        1        0   
243       18.78  3.00     2           1         1        0        0        0   

     time_Dinner  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
239            1  
240            1  
241            1  
242            1  
243            1  

[244 rows x 9 columns]

In [78]:
x = df_encode.drop('tip', axis = 1)
y = df_encode['tip']


In [80]:
x
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [52]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)


In [81]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=42)

In [54]:
x_train_transformed = ohe.fit_transform(x_train[['sex','day', 'time']])

In [56]:
x_train_transformed.shape

(163, 5)

In [57]:
x_test_transformed = ohe.fit_transform(x_test[['sex','day', 'time']])
x_test_transformed

array([[1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0.

In [82]:
from sklearn.ensemble import RandomForestRegressor
model_regressor = RandomForestRegressor()


In [87]:
from sklearn.model_selection import GridSearchCV
params = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_depth': [1,2,3,4,5,6,7],
}

grid_search = GridSearchCV(estimator=model_regressor, param_grid=params, cv = 5, scoring='neg_mean_squared_error')
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7]},
             scoring='neg_mean_squared_error')

In [88]:
grid_search.best_params_

{'criterion': 'absolute_error', 'max_depth': 3}

In [89]:
y_pred = grid_search.predict(x_test)
y_pred

array([3.209  , 1.9522 , 3.91505, 3.80835, 2.0295 , 3.22785, 3.3595 ,
       2.01025, 2.1989 , 2.1338 , 3.2443 , 1.96585, 1.97105, 2.2289 ,
       1.71475, 3.2498 , 3.24305, 3.28545, 3.0623 , 4.9362 , 3.7528 ,
       3.2938 , 2.08965, 1.767  , 3.2893 , 1.99225, 2.15635, 3.2871 ,
       3.507  , 6.4066 , 4.05935, 1.802  , 3.68255, 3.19255, 3.1297 ,
       3.889  , 2.04355, 4.48205, 2.0295 , 3.25085, 1.96585, 2.0635 ,
       3.3284 , 2.13615, 1.95135, 1.6318 , 1.98465, 3.24375, 1.62755,
       2.02575, 3.28985, 3.31195, 4.3742 , 2.15625, 3.2244 , 2.0103 ,
       2.0982 , 3.2222 , 3.23705, 2.07275, 4.26485, 3.18545, 3.31195,
       2.65895, 3.209  , 3.2422 , 2.06285, 1.6265 , 3.3351 , 3.36985,
       3.7725 , 3.96085, 3.1797 , 3.19885, 2.03835, 3.75295, 4.24845,
       3.92245, 4.2828 , 4.36335, 1.6451 ])

In [91]:
from sklearn.metrics import mean_squared_error
score = mean_squared_error(y_pred, y_test)
score

0.8547167216975307

In [98]:
df1= sns.load_dataset('tips')
df1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [100]:
X = df1.drop('tip', axis = 1)
Y = df1['tip']

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [101]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size= 0.33, random_state=42)


In [102]:
from sklearn.compose import ColumnTransformer
clt = ColumnTransformer(
            transformers=[
                ('tnf1', OneHotEncoder(drop='first', sparse_output= False),['sex', 'smoker', 'day', 'time'])
            ],
    remainder='passthrough'
)

In [105]:
x_train_new = clt.fit_transform(x_train)

In [108]:
x_test_new =clt.fit_transform(x_test)

In [109]:
x_test_new.shape

(81, 8)

In [110]:
x_train_new.shape

(163, 8)

In [113]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()

In [115]:
from sklearn.model_selection import GridSearchCV
params = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_depth': [1,2,3,4,5,6,7],
}

c_model = GridSearchCV(estimator=model, param_grid=params, cv = 5, scoring='neg_mean_squared_error')
c_model.fit(x_train_new, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7]},
             scoring='neg_mean_squared_error')

In [116]:
c_model.best_params_

{'criterion': 'squared_error', 'max_depth': 3}

In [117]:
y_pred = grid_search.predict(x_test_new)
y_pred

/Users/krishprakash/Desktop/ML/env/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([1.91745, 1.72515, 1.72515, 1.91745, 1.8819 , 1.72515, 1.8819 ,
       1.8819 , 1.72515, 1.9337 , 1.72515, 1.91745, 1.8819 , 1.72515,
       1.8819 , 1.8819 , 1.8819 , 1.72515, 1.91745, 1.8819 , 1.91745,
       1.91745, 1.91745, 1.91745, 1.72515, 1.8819 , 1.72515, 1.91745,
       1.72515, 1.72515, 1.72515, 1.91745, 1.91745, 1.91745, 1.72515,
       1.8819 , 1.9337 , 1.8819 , 1.8819 , 1.91745, 1.91745, 1.8819 ,
       1.72515, 1.72515, 1.8819 , 1.91745, 1.91745, 1.91745, 1.8819 ,
       1.91745, 1.91745, 1.9337 , 1.72515, 1.8819 , 1.72515, 1.8819 ,
       1.72515, 1.91745, 1.72515, 1.91745, 1.72515, 1.72515, 1.72515,
       1.9375 , 1.91745, 1.91745, 1.91745, 1.91745, 1.91745, 1.72515,
       1.72515, 1.91745, 1.8819 , 1.91745, 1.91745, 1.91745, 1.72515,
       1.72515, 1.91745, 1.8819 , 1.8819 ])

In [123]:
from sklearn.metrics import mean_squared_error, r2_score
score = mean_squared_error(y_test, y_pred)
score


2.3375662800308654

In [124]:
r2score = r2_score(y_test, y_pred)
r2score

-0.8017011030754795

In [125]:
######### random forest regressor complete